import type { Lead } from "./types"

export const mockLeads: Lead[] = [
  {
    id: "lead-001",
    name: "Sarah Johnson",
    phone: "+1 (555) 123-4567",
    message: "Hi, I'm interested in your premium subscription plan. Can you share more details about pricing?",
    source: "WhatsApp Campaign",
    status: "new",
    tags: ["hot", "vip"],
    assignedTo: null,
    notes: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: "lead-002",
    name: "Michael Chen",
    phone: "+1 (555) 234-5678",
    message: "Looking for enterprise solutions for my team of 50+. What options do you have?",
    source: "Website Form",
    status: "contacted",
    tags: ["hot", "urgent"],
    assignedTo: "Alex Rivera",
    notes: ["Called back, very interested in enterprise tier"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: "lead-003",
    name: "Emma Wilson",
    phone: "+1 (555) 345-6789",
    message: "Do you offer monthly payment plans? I need flexibility.",
    source: "WhatsApp Direct",
    status: "qualified",
    tags: ["warm", "follow-up"],
    assignedTo: "Jordan Kim",
    notes: ["Interested in monthly plan", "Budget around $500/mo"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
  },
  {
    id: "lead-004",
    name: "David Park",
    phone: "+1 (555) 456-7890",
    message: "Just browsing for now, but your product looks interesting.",
    source: "WhatsApp Campaign",
    status: "new",
    tags: ["cold"],
    assignedTo: null,
    notes: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
  {
    id: "lead-005",
    name: "Lisa Anderson",
    phone: "+1 (555) 567-8901",
    message: "Ready to purchase! Please send me the payment link.",
    source: "Referral",
    status: "converted",
    tags: ["hot", "vip"],
    assignedTo: "Alex Rivera",
    notes: ["Referred by Michael Chen", "Purchased premium annual plan"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "lead-006",
    name: "James Martinez",
    phone: "+1 (555) 678-9012",
    message: "Can I get a demo of your platform?",
    source: "WhatsApp Direct",
    status: "contacted",
    tags: ["warm"],
    assignedTo: "Jordan Kim",
    notes: ["Demo scheduled for next week"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
  },
  {
    id: "lead-007",
    name: "Amanda Thompson",
    phone: "+1 (555) 789-0123",
    message: "Not interested anymore, found another solution.",
    source: "WhatsApp Campaign",
    status: "lost",
    tags: ["cold"],
    assignedTo: "Alex Rivera",
    notes: ["Went with competitor", "Price was main concern"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: "lead-008",
    name: "Robert Garcia",
    phone: "+1 (555) 890-1234",
    message: "Need urgent help setting up my account. Can someone call me ASAP?",
    source: "WhatsApp Direct",
    status: "new",
    tags: ["hot", "urgent"],
    assignedTo: null,
    notes: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
]

export const teamMembers = ["Alex Rivera", "Jordan Kim", "Sam Taylor", "Morgan Lee"]
